// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Drop struct {
	ID                string
	Filename          string
	StoredName        string
	FileSize          int64
	MimeType          string
	IsText            bool
	TextContent       pgtype.Text
	BurnAfterDownload bool
	DownloadCount     int32
	ExpiresAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}
