// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDrop = `-- name: CreateDrop :one
INSERT INTO drops (
  id,
  filename,
  stored_name,
  file_size,
  mime_type,
  is_text,
  text_content,
  burn_after_download,
  expires_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9
)
RETURNING id, filename, stored_name, file_size, mime_type, is_text, text_content, burn_after_download, download_count, expires_at, created_at
`

type CreateDropParams struct {
	ID                string
	Filename          string
	StoredName        string
	FileSize          int64
	MimeType          string
	IsText            bool
	TextContent       pgtype.Text
	BurnAfterDownload bool
	ExpiresAt         time.Time
}

func (q *Queries) CreateDrop(ctx context.Context, arg CreateDropParams) (Drop, error) {
	row := q.db.QueryRow(ctx, createDrop,
		arg.ID,
		arg.Filename,
		arg.StoredName,
		arg.FileSize,
		arg.MimeType,
		arg.IsText,
		arg.TextContent,
		arg.BurnAfterDownload,
		arg.ExpiresAt,
	)
	var i Drop
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.StoredName,
		&i.FileSize,
		&i.MimeType,
		&i.IsText,
		&i.TextContent,
		&i.BurnAfterDownload,
		&i.DownloadCount,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDrop = `-- name: DeleteDrop :one
DELETE FROM drops
WHERE id = $1
RETURNING stored_name
`

func (q *Queries) DeleteDrop(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, deleteDrop, id)
	var stored_name string
	err := row.Scan(&stored_name)
	return stored_name, err
}

const deleteExpiredDrops = `-- name: DeleteExpiredDrops :many
DELETE FROM drops
WHERE expires_at <= NOW()
RETURNING id, stored_name
`

type DeleteExpiredDropsRow struct {
	ID         string
	StoredName string
}

func (q *Queries) DeleteExpiredDrops(ctx context.Context) ([]DeleteExpiredDropsRow, error) {
	rows, err := q.db.Query(ctx, deleteExpiredDrops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteExpiredDropsRow
	for rows.Next() {
		var i DeleteExpiredDropsRow
		if err := rows.Scan(&i.ID, &i.StoredName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDropByID = `-- name: GetDropByID :one
SELECT id, filename, stored_name, file_size, mime_type, is_text, text_content, burn_after_download, download_count, expires_at, created_at FROM drops
WHERE id = $1 AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetDropByID(ctx context.Context, id string) (Drop, error) {
	row := q.db.QueryRow(ctx, getDropByID, id)
	var i Drop
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.StoredName,
		&i.FileSize,
		&i.MimeType,
		&i.IsText,
		&i.TextContent,
		&i.BurnAfterDownload,
		&i.DownloadCount,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementDownloadCount = `-- name: IncrementDownloadCount :exec
UPDATE drops
SET download_count = download_count + 1
WHERE id = $1
`

func (q *Queries) IncrementDownloadCount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrementDownloadCount, id)
	return err
}

const listActiveDrops = `-- name: ListActiveDrops :many
SELECT id, filename, stored_name, file_size, mime_type, is_text, text_content, burn_after_download, download_count, expires_at, created_at FROM drops
WHERE expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) ListActiveDrops(ctx context.Context) ([]Drop, error) {
	rows, err := q.db.Query(ctx, listActiveDrops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Drop
	for rows.Next() {
		var i Drop
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.StoredName,
			&i.FileSize,
			&i.MimeType,
			&i.IsText,
			&i.TextContent,
			&i.BurnAfterDownload,
			&i.DownloadCount,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
